name: deploy-foundryvtt

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  LOCATION: ${{ vars.LOCATION }}
  STORAGE_CONFIGURATION: ${{ vars.STORAGE_CONFIGURATION }}
  # The type of Azure service to deploy the resources to.
  # ACI = Azure Container Instance
  # AAS = Azure App Service (Web App)
  TYPE: ${{ vars.TYPE }}

  # Only required if TYPE is ACI
  CONTAINER_CONFIGURATION: ${{ vars.CONTAINER_CONFIGURATION }}

  # Only required if TYPE is AAS
  APPSERVICEPLAN_CONFIGURATION: ${{ vars.APPSERVICEPLAN_CONFIGURATION }}
  DEPLOY_DDBPROXY: ${{ vars.DEPLOY_DDBPROXY }}

jobs:
  deploy-aas:
    if: env.Type == 'AAS'
    uses: ./.github/workflows/deploy-aas.yml
    with:
      LOCATION: ${{ env.LOCATION }}
      BASE_RESOURCE_NAME: ${{ env.BASE_RESOURCE_NAME }}
      RESOURCE_GROUP_NAME: ${{ env.RESOURCE_GROUP_NAME }}
      STORAGE_CONFIGURATION: ${{ env.STORAGE_CONFIGURATION }}
      APPSERVICEPLAN_CONFIGURATION: ${{ env.APPSERVICEPLAN_CONFIGURATION }}
      DEPLOY_DDBPROXY: ${{ env.DEPLOY_DDBPROXY }}
    secrets:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      FOUNDRY_USERNAME: ${{ secrets.FOUNDRY_USERNAME }}
      FOUNDRY_PASSWORD: ${{ secrets.FOUNDRY_PASSWORD }}
      FOUNDRY_ADMIN_KEY: ${{ secrets.FOUNDRY_ADMIN_KEY }}

  deploy-aci:
    if: env.Type == 'ACI'
    uses: ./.github/workflows/deploy-aci.yml
    with:
      location: ${{ env.LOCATION }}
      BASE_RESOURCE_NAME: ${{ env.BASE_RESOURCE_NAME }}
      RESOURCE_GROUP_NAME: ${{ env.RESOURCE_GROUP_NAME }}
      STORAGE_CONFIGURATION: ${{ env.STORAGE_CONFIGURATION }}
      CONTAINER_CONFIGURATION: ${{ env.$CONTAINER_CONFIGURATION }}
    secrets:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      FOUNDRY_USERNAME: ${{ secrets.FOUNDRY_USERNAME }}
      FOUNDRY_PASSWORD: ${{ secrets.FOUNDRY_PASSWORD }}
      FOUNDRY_ADMIN_KEY: ${{ secrets.FOUNDRY_ADMIN_KEY }}
